replicaCount: 1  # start with 1 pod

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

image:
  repository: us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend
  tag: "1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

labels:
  my-frontend: app-frontend

nodeSelector:
  kubernetes.io/hostname: frontend

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

namespace: frontend
